# SPDX-License-Identifier: MIT
---
# tasks file for tetsuyainfra.kopia_install
# - name: KopiaInstall | Show variables
#   ansible.builtin.debug:
#     msg: "kopia_install: {{ kopia_install }}, kopia_uninstall: {{ kopia_uninstall }}, kopia_install_become: {{ kopia_install_become }}"
# - name: KopiaInstall | Show variables
#   ansible.builtin.debug:
#     var: ansible_connection

- name: KopiaInstall | Include OS specific main({{ ansible_facts['os_family'] }})
  ansible.builtin.include_tasks: "main_{{ ansible_facts['os_family'] }}.yml"
